
server:
 port: 8060



     
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      
managemnet:
  tracing:
    sampling:
    probability: 1.0
  
   


